name: Auto Release

on:
  push:
    branches:
      - master  # Schimbă la branch-ul tău principal, dacă este diferit

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Obține informații despre branch și commit
      - name: Get the Commit Information
        id: commit_info
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Creează un release
      - name: Create a Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: "v1.0.${{ github.run_number }}"  # Definește un tag pentru release
          release_name: "Release v1.0.${{ github.run_number }}"
          body: |
            Commit: ${{ env.COMMIT_HASH }}
            Mesaj: ${{ env.COMMIT_MESSAGE }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token pentru autentificare
