name: Auto Release

on:
  push:
    branches:
      - master  # Replace with your actual branch name

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Get information about branch and commit
      - name: Get the Commit Information
        id: commit_info
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Create a Release (Optional Draft)
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          # You can use semantic versioning or integrate with your codebase here
          tag_name: "v1.${{ github.run_number }}"  # Update versioning as needed
          release_name: "Release v1.${{ github.run_number }}"  # Update versioning as needed
          body: |
            Commit: ${{ env.COMMIT_HASH }}
            Message: ${{ env.COMMIT_MESSAGE }}
          draft: ${{ inputs.create_draft_release || false }}  # Optional draft release
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
