name: Auto Release

on:
  push:
    branches:
      - main  # Schimbă la branch-ul tău principal, dacă este diferit

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Obține informații despre commit
      - name: Obține Informații despre Commit
        id: commit_info
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Creează un tag pentru release
      - name: Setează Tag-ul
        run: |
          TAG="v1.0.${{ github.run_number }}"
          echo "TAG=$TAG" >> $GITHUB_ENV

      # Creează un release
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}  # Tag-ul pentru release
          body: |
            Commit: ${{ env.COMMIT_HASH }}
            Mesaj: ${{ env.COMMIT_MESSAGE }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token pentru autentificare
