name: Auto Release

on:
  push:
    branches:
      - master  # Replace with your actual branch name

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Get information about branch and commit
      - name: Get the Commit Information
        id: commit_info
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Create a Release (Optional Draft)
      - name: Create a Release (using Node.js 20)
        uses: actions/create-release@v4  # Official GitHub action, compatible with Node.js 20
        with:
          tag_name: "v1.${{ github.run_number }}"  # Consider semantic versioning for real-world scenarios
          release_name: "Release v1.${{ github.run_number }}"  # Consider semantic versioning
          body: |
            Commit: ${{ env.COMMIT_HASH }}
            Message: ${{ env.COMMIT_MESSAGE }}
          draft: ${{ inputs.create_draft_release || false }}  # Optional draft release
          prerelease: false  # Change to true if releasing a pre-release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
