name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Get GitHub Build Number
      - name: Get Build Number
        id: build_number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      # Log into Docker Hub
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      # Build the Docker image
      - name: Build Docker Image
        run: |
          TAG="v1.0.${{ github.run_number }}"
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/openvpn-as:${TAG}

      # Push the Docker image to the repository
      - name: Docker Push
        run: |
          TAG="v1.0.${{ github.run_number }}"
          docker push ${{ secrets.DOCKER_USERNAME }}/openvpn-as:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/openvpn-as:latest
