name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      # Obține numărul de build GitHub
      - name: Obține Build Number
        id: build_number
        run: echo "::set-output name=number::${{ github.run_number }}"

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # Construiește și etichetează imaginea cu versiunea specificată
      - name: Build the Docker image
        run: |
          TAG="v1.0.${{ steps.build_number.outputs.number }}"
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/openvpn-as:${TAG}

      # Etichetează și cu "latest" pentru comoditate, dar principalul tag va fi versiunea numerotată
      - name: Docker Push
        run: |
          TAG="v1.0.${{ steps.build_number.outputs.number }}"
          docker push ${{ secrets.DOCKER_USER }}/openvpn-as:${TAG}
          docker push ${{ secrets.DOCKER_USER }}/openvpn-as:latest
