nume: CI pentru Imagini Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    pași:
      - name: Verificare Repo
        uses: actions/checkout@v4

      # Obține numărul de build
      - name: Obține Număr de Build
        id: build_number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      # Autentificare pe Docker Hub cu o metodă sigură
      - name: Autentificare Docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Construiește imaginea Docker
      - name: Construiește Imaginea Docker
        run: |
          TAG="v1.0.${{ github.run_number }}"
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/openvpn-as:${TAG}

      # Publică imaginea Docker pe repository
      - name: Publică Docker
        run: |
          TAG="v1.0.${{ github.run_number }}"
          docker push ${{ secrets.DOCKER_USERNAME }}/openvpn-as:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/openvpn-as:latest
