name: External Trigger Scheduler

on:
  schedule:
    - cron:  '0 3 15 * *'
  workflow_dispatch:

jobs:
  external-trigger-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: External Trigger Scheduler
        run: |
          echo "**** Declanșare verificare versiune nouă OpenVPN AS (lunar) ****"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref":"master"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/external_trigger.yml/dispatches
          echo "**** Trigger trimis cu succes ****"
