name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v3
      with:
        issue-message: 'Mulțumim că ai deschis primul tău issue! Te rugăm să urmezi template-ul pentru [bug](https://github.com/levinetit/openvpn-as/blob/master/.github/ISSUE_TEMPLATE/issue.bug.md) sau [feature request](https://github.com/levinetit/openvpn-as/blob/master/.github/ISSUE_TEMPLATE/issue.feature.md).'
        pr-message: 'Mulțumim pentru acest pull request! Te rugăm să urmezi [template-ul pentru PR](https://github.com/levinetit/openvpn-as/blob/master/.github/PULL_REQUEST_TEMPLATE.md).'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
