name: Package Trigger Scheduler

on:
  schedule:
    - cron: '00 2 * * 6'
  workflow_dispatch:

jobs:
  package-trigger-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package Trigger Scheduler
        run: |
          echo "**** Declanșare rebuild săptămânal imagine Docker ****"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref":"master"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/docker-image.yml/dispatches
          echo "**** Rebuild declanșat cu succes ****"
