name: Package Trigger Main

on:
  workflow_dispatch:

jobs:
  package-trigger-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package Trigger
        if: github.ref == 'refs/heads/master'
        run: |
          if [ -n "${{ secrets.PAUSE_PACKAGE_TRIGGER_OPENVPN_AS_MASTER }}" ]; then
            echo "**** Trigger dezactivat via secret PAUSE_PACKAGE_TRIGGER_OPENVPN_AS_MASTER ****"
            exit 0
          fi
          echo "**** Declanșare rebuild imagine Docker ****"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref":"master"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/docker-image.yml/dispatches
          echo "**** Rebuild declanșat cu succes ****"
