#!/usr/bin/with-contenv bash

# Crearea directoriilor necesare
mkdir -p /openvpn/pid /openvpn/sock /openvpn/tmp /dev/net /config/log /config/etc/tmp

# Crearea dispozitivului tun dacă nu există
if [ ! -c /dev/net/tun ]; then
  mknod /dev/net/tun c 10 200
fi

echo "Please login with the originally generated password. Please make sure to change it. If you have already changed it, please disregard"
grep -i 'password.$' /usr/local/openvpn_as/init.log

# Instalare sau actualizare openvpn-as
if [ -f /version.txt ]; then
	OPENVPNAS_VERSION=$(cat /version.txt)
	rm -rf /usr/local/openvpn_as
	ln -s /config /usr/local/openvpn_as
	if [ ! -f /config/etc/as.conf ]; then
		echo "installing openvpn-as for the first time"
		apt-get update && \
		apt-get install -y \
			openvpn-as=$OPENVPNAS_VERSION
		echo "Stopping openvpn-as now; will start again later after configuring"
		kill `cat /var/run/openvpnas.pid`
		rm /version.txt
		sed -i \
			-e 's#=openvpn_as#=abc#g' \
			-e 's#~/tmp#/openvpn/tmp#g' \
			-e 's#~/sock#/openvpn/sock#g' \
			/usr/local/openvpn_as/etc/as_templ.conf
	else
		echo "existing data found, reinstalling openvpn-as"
		mkdir -p /config/backup
		cd /config/etc/db || exit
		DBFILESBAK="*.db"
		for f in $DBFILESBAK
		do
			echo "backing up $f"
			sqlite3 "$f" .dump > /config/backup/"$f"
		done
		echo "backing up as.conf"
		cp /config/etc/as.conf /config/backup/as.conf
		cd /config || exit
		for dir in *; do
            if [[ $dir != "backup" && $dir != "log" && $dir != "custom-cont-init.d" && $dir != "custom-services.d" ]]; then
                rm -rf "$dir"
            fi
        done
		apt-get update && \
		apt-get install -y \
			openvpn-as=$OPENVPNAS_VERSION
		echo "Stopping openvpn-as now; will start again later after configuring"
		kill `cat /var/run/openvpnas.pid`
		rm /version.txt
		sed -i \
			-e 's#=openvpn_as#=abc#g' \
			-e 's#~/tmp#/openvpn/tmp#g' \
			-e 's#~/sock#/openvpn/sock#g' \
			/usr/local/openvpn_as/etc/as_templ.conf
		cd /config/backup || exit
		DBFILERES="*.db"
		for f in $DBFILERES
		do
			echo "restoring $f"
			rm -f /config/etc/db/"$f"
			sqlite3 </config/backup/"$f" /config/etc/db/"$f"
		done
		rm -f /config/etc/as.conf
		echo "restoring as.conf"
		cp /config/backup/as.conf /config/etc/as.conf
		rm -rf /config/backup
	fi
fi

# Copierea conținutului din /usr/local/openvpn_as în /config
cp -R /usr/local/openvpn_as/* /config

# Ștergerea fișierelor vechi de tip sock
for file in /openvpn/sock/*
	do
		if [ -e "$file" ]; then
		rm -rf "$file"
		fi
	done

# Ștergerea fișierelor vechi de tip pid
for file in /openvpn/pid/*
	do
		if [ -e "$file" ]; then
		rm -rf "$file"
		fi
	done

# Stabilirea permisiunilor adecvate pe directoarele configurate
chown abc:abc /config/log /config/etc/tmp
chmod -R 755 /openvpn
