#!/usr/bin/with-contenv bash

# Crează directoarele necesare
mkdir -p /openvpn/{pid,sock,tmp} /dev/net /config/log /config/etc/tmp

# Crează dispozitivul tun dacă nu există
if [ ! -c /dev/net/tun ]; then
  mknod /dev/net/tun c 10 200
fi

# Afișează parola inițială generată pentru OpenVPN-AS
echo "Vă rugăm să vă autentificați cu parola inițială generată.
Asigurați-vă că o schimbați ulterior. Dacă ați schimbat deja parola, vă rugăm să ignorați acest mesaj."
grep -i 'password.$' /usr/local/openvpn_as/init.log

# Verifică existența fișierului de versiune și instalează/actualizează OpenVPN-AS
if [ -f /version.txt ]; then
	OPENVPNAS_VERSION=$(cat /version.txt)
	rm -rf /usr/local/openvpn_as
	ln -s /config /usr/local/openvpn_as
	if [ ! -f /config/etc/as.conf ]; then
		echo "Se instalează OpenVPN-AS pentru prima dată"
		apt-get update && \
		apt-get install -y \
			openvpn-as="$OPENVPNAS_VERSION"
		echo "Se oprește OpenVPN-AS acum; va fi repornit mai târziu după configurare"
		kill "$(cat /var/run/openvpnas.pid)"
		rm /version.txt
		sed -i \
			-e 's#=openvpn_as#=abc#g' \
			-e 's#~/tmp#/openvpn/tmp#g' \
			-e 's#~/sock#/openvpn/sock#g' \
			/usr/local/openvpn_as/etc/as_templ.conf
	else
		echo "Date existente găsite, se reinstalează OpenVPN-AS"
		mkdir -p /config/backup
		cd /config/etc/db || exit
		DBFILESBAK="*.db"
		for f in $DBFILESBAK
		do
			echo "Se face backup pentru $f"
			sqlite3 "$f" .dump > /config/backup/"$f"
		done
		echo "Se face backup pentru as.conf"
		cp /config/etc/as.conf /config/backup/as.conf
		cd /config || exit
		shopt -s extglob
		rm -rf !(backup|log|custom-cont-init.d|custom-services.d)
		shopt -u extglob
		apt-get update && \
		apt-get install -y \
			openvpn-as="$OPENVPNAS_VERSION"
		echo "Se oprește OpenVPN-AS acum; va fi repornit mai târziu după configurare"
		kill "$(cat /var/run/openvpnas.pid)"
		rm /version.txt
		sed -i \
			-e 's#=openvpn_as#=abc#g' \
			-e 's#~/tmp#/openvpn/tmp#g' \
			-e 's#~/sock#/openvpn/sock#g' \
			/usr/local/openvpn_as/etc/as_templ.conf
		cd /config/backup || exit
		DBFILERES="*.db"
		for f in $DBFILERES
		do
			echo "Se restaurează $f"
			rm -f /config/etc/db/"$f"
			sqlite3 < /config/backup/"$f" /config/etc/db/"$f"
		done
		rm -f /config/etc/as.conf
		echo "Se restaurează as.conf"
		cp /config/backup/as.conf /config/etc/as.conf
		rm -rf /config/backup
	fi
fi

# Șterge fișierele vechi de tip sock și pid
rm -rf /openvpn/sock/*
rm -rf /openvpn/pid/*

# Setează permisiunile adecvate
chown abc:abc /config/log /config/etc/tmp
chmod -R 755 /openvpn
