#!/usr/bin/with-contenv bash

# Afișează informații despre imagine la pornire
echo '
───────────────────────────────────────
  OpenVPN Access Server - levinetit
  Ubuntu 26.04 | Python 3.14 | v3.2.1
  https://github.com/levinetit/openvpn-as
───────────────────────────────────────'
