#!/usr/bin/with-contenv bash

# Afișează informații despre imagine la pornire
echo '
───────────────────────────────────────
  OpenVPN Access Server - levinetit
  Ubuntu 24.04 | Python 3.12 | v3.1.0
  https://github.com/levinetit/openvpn-as
───────────────────────────────────────'
